Added test cases for StylesContext
tjtanjin/react-chatbotify pull request #236
Opened 2024-10-20 14:41 UTC by Suvrat1629

#### Description

Please include a brief summary of the change and include the relevant issue(s).

Closes #232 

#### What change does this PR introduce?
I have added a context folder and added a StylesContext.test.tsx file which contains test code for StylesContext.

Please select the relevant option(s).

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (changes to docs/code comments)

#### What is the proposed approach?

Please give a short overview/explanation on the approach taken to resolve the issue(s).

#### Checklist:

- [x] The commit message follows our adopted [guidelines](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Testing has been done for the change(s) added (for bug fixes/features)
- [ ] Relevant comments/docs have been added/updated (for bug fixes/features)

2024-10-21 15:36 UTC, tjtanjin requested changes
Hey @Suvrat1629, thank you for the PR. I've left a couple of comments to be addressed. Let me know if you need any clarifications 😊

2024-10-21 15:36 UTC, tjtanjin commented on package.json
> +    "@types/testing-library__react-hooks": "^3.4.1",
This package is deprecated, we don't need to install it.

2024-10-21 15:36 UTC, tjtanjin commented on src/components/ChatBotLoader.tsx
> -
It's visually convenient to leave a line between react imports and our own imports, so let's keep this space there.

2024-10-21 16:01 UTC, Suvrat1629 commented
I have made the changes as you told me please tell me if you need me to make anymore changes

2024-10-22 13:21 UTC, tjtanjin commented
> I have made the changes as you told me please tell me if you need me to make anymore changes

Hey @Suvrat1629, there're still outstanding comments unresolved 😅

2024-10-24 15:23 UTC, Suvrat1629 commented
@tjtanjin updates?

2024-10-26 07:00 UTC, tjtanjin approved these changes
LGTM!

2024-10-26 07:00 UTC, merged