Add unit tests for VoiceButton component
tjtanjin/react-chatbotify pull request #255
Opened 2024-10-31 19:09 UTC by Elisassa

#### Description

This PR introduces unit tests for the VoiceButton component. 

Closes [#137](https://github.com/tjtanjin/react-chatbotify/issues/137)

#### What change does this PR introduce?

Please select the relevant option(s).

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (changes to docs/code comments)

#### What is the proposed approach?

The tests validate that the VoiceButton component renders correctly with the appropriate aria-label, initial state, and styles. This change aims to increase code coverage and ensure that the VoiceButton behaves as expected.

#### Checklist:

- [ ] The commit message follows our adopted [guidelines](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Testing has been done for the change(s) added (for bug fixes/features)
- [ ] Relevant comments/docs have been added/updated (for bug fixes/features)

2024-11-01 00:36 UTC, tjtanjin requested changes
Hey @Elisassa! Thanks for the PR. Some quick comments:
- Lint is failing (remove unused imports)
- Since this is a toggle button, it would be useful to have test cases for testing toggle on/off, similar to what audio/notification button tests have. You can take reference here: https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/components/buttons/NotificationButton.test.tsx

Since hacktoberfest is ending in a couple hours, I'll add the `hacktoberfest-accepted` label first so your efforts won't go wasted!

2024-11-04 15:25 UTC, tjtanjin commented
Hey @Elisassa, would you still be keen to work on this issue? 🥹

2024-11-04 15:33 UTC, Elisassa commented
Hi  ! I will be working on this and will do my best to finish by the end of Friday!!

2024-11-04 15:41 UTC, tjtanjin commented
> Hi ! I will be working on this and will do my best to finish by the end of Friday!!

No worries! Happy to hear! 😊

2024-12-18 17:31 UTC, tjtanjin commented
This pull request is stale and its associated issue has been resolved with #287. Closing this but thank you for your time! @Elisassa

2024-12-18 17:31 UTC, closed without merging